#!/usr/bin/env bash
set -euo pipefail

# If staged files contain changes in yaml files: Run linting
if git diff --name-only --cached | grep -E '\.(yaml|yml)' > /dev/null; then
  make lint -o install -j "$(nproc)"
fi
