#!/usr/bin/env ansible-playbook
- hosts: all
  vars_files:
    - become-password.secret
  roles:
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
      homebrew_brewfile_dir: ansible_env.PWD
  tasks:
    - import_tasks: tasks/oh-my-zsh.yml
      tags: ["oh-my-zsh"]
    - import_tasks: tasks/dotfiles.yml
      tags: ["dotfiles"]
