#!/usr/bin/env ansible-playbook
- name: Main Playbook
  hosts: all
  vars_files:
    - become-password.secret
  roles:
    - role: geerlingguy.mac.homebrew
      homebrew_brewfile_dir: ansible_env.PWD
      tags:
        - homebrew
  tasks:
    - name: Zsh
      ansible.builtin.import_tasks: tasks/oh-my-zsh.yml
      tags:
        - oh-my-zsh
    - name: Dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles
    - name: Python packages
      ansible.builtin.pip:
        name:
          # Install python package for python-based NeoVim plugins.
          - pynvim
      tags:
        - pip
