[project]
name = "dotfiles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "ansible-core>=2.19.2",
]

[dependency-groups]
dev = [
    "ansible-lint>=25.8.2",
]
