collections:
  - name: community.general
    version: 9.0.0
  - name: geerlingguy.mac
    version: 4.0.0
roles:
  - name: gantsign.oh-my-zsh
    version: 2.7.0
  - name: elliotweiser.osx-command-line-tools
    version: 2.3.0
