collections:
  - name: community.general
    version: 10.7.1
  - name: geerlingguy.mac
    version: 4.1.0
roles:
  - name: elliotweiser.osx-command-line-tools
    version: 2.3.0
  - name: gantsign.oh-my-zsh
    version: 2.7.0
