collections:
  - name: community.general
    version: 7.5.1
  - name: geerlingguy.mac
    version: 2.1.3
roles:
  - name: gantsign.oh-my-zsh
    version: 2.7.0
  - name: elliotweiser.osx-command-line-tools
    version: 2.3.0
