collections:
  - name: community.general
    version: 7.4.0
  - name: geerlingguy.mac
    version: 2.1.1
roles:
  - name: gantsign.oh-my-zsh
    version: 2.3.0
  - name: elliotweiser.osx-command-line-tools
    version: 2.3.0
