# Required for selene
# See https://github.com/folke/twilight.nvim/blob/1584c0b0a979b71fd86b18d302ba84e9aba85b1b/vim.toml
[selene]
base = "lua51"
name = "vim"

[vim]
any = true

[jit]
any = true

[assert]
any = true

[describe]
any = true

[it]
any = true
