- name: Set fact for dotfiles path
  ansible.builtin.set_fact:
    # NOTE: Do keep the slash at the end!
    dotfiles_path: "{{ ansible_env.PWD }}/files/dotfiles/"

- name: Find all dotfiles directories
  ansible.builtin.find: &findParams
    paths: "{{ dotfiles_path }}"
    file_type: directory
    recurse: true
    hidden: true
  register: dotfiles_directories

- name: Ensure paths for dotfiles exist
  ansible.builtin.file:
    path: "~/{{ item.path | replace(dotfiles_path, '') }}"
    state: directory
    mode: 0755
  with_items: "{{ dotfiles_directories.files }}"

- name: Find all dotfiles to be linked
  ansible.builtin.find:
    <<: *findParams
    file_type: file
  register: dotfiles

- name: Symlink dotfiles
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "~/{{ item.path | replace(dotfiles_path, '') }}"
    state: link
    force: true
  with_items: "{{ dotfiles.files }}"
