- name: Omz should be installed and configured
  ansible.builtin.import_role:
    name: gantsign.oh-my-zsh
  vars:
    # oh_my_zsh_theme: romkatv/powerlevel10k
    oh_my_zsh_install: true
    users:
      - username: "{{ ansible_user_id }}"

- name: Omz plugins should be installed
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "~/.oh-my-zsh/custom/plugins/{{ item | regex_replace('.*\\/(.*)\\.git', '\\1') }}"
    force: true
  loop:
    - https://github.com/lukechilds/zsh-nvm.git

# - name: iTerm custom settings file should be set
#   osx_defaults:
#     domain: com.googlecode.iterm2
#     key: PrefsCustomFolder
#     type: string
#     value: "{{ ansible_env.PWD }}/roles/js_mac/files"
