- name: Omz should be installed and configured
  ansible.builtin.import_role:
    name: gantsign.oh-my-zsh
  vars:
    oh_my_zsh_install: true
    users:
      - username: "{{ ansible_user_id }}"

- name: Omz plugins should be installed
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "~/.oh-my-zsh/custom/plugins/{{ item | regex_replace('.*\\/(.*)\\.git', '\\1') }}"
    force: true
  loop:
    - https://github.com/lukechilds/zsh-nvm.git
    - https://github.com/wfxr/forgit.git
